### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by bauersfeld** [Laravel-Backpack/PageManager#14]
I ran composer update on my Backpack demo project and now the route for /admin/page results in a 404.  It was working fine before the update. I'm using the Backpack 3.0 Demo. I think it has something to do with the new Laravel 5.3 route changes.  .... any thoughts?

**Comment by pushamaku** [comment]
In: vendor/backpack/pagemanager/src/PageManagerServiceProvider.php

Change:

`Route::group(['middleware' => ['web', 'admin'], 'prefix' => config('backpack.base.route_prefix')], function () {`

To:

`Route::group(['middleware' => ['web', 'auth'], 'prefix' => config('backpack.base.route_prefix', 'admin')], function () {`

**Comment by tabacitu** [comment]
Huh. @bauersfeld , does @pushamaku 's fix work for you?

**Comment by bauersfeld** [comment]
yes, thank you.  Will it get fixed in the master branch?

btw, congrats on backpack - it's a very well designed crud package!

**Comment by arielvsp** [comment]
Hi there,
Have the same problem. Fresh install of Backpack + PageManager on Laravel 5.2, followed the guidelines, including the above fix. Still getting 404. Any ideas on what might go wrong or how to further debug this?

**Comment by tabacitu** [comment]
@arielvsp , unfortunately I can't push this fix for you in 5.2. Backpack on Laravel 5.2 is considered deprecated and won't receive updates anytime soon. It's very difficult to maintain and support the 5.3 version alone, pushing all the updates into the separate 5.2 branches and supporting them would require a kind of manpower we just don't have. 

I recommend you update to Laravel 5.3 or use the "admin" prefix, that should still be working.

Cheers!

PS. For future reference, the bug has been fixed for Laravel 5.3 in this commit: af7fada8115f305c55bc43b6ca4d03364a00f464

**Comment by tabacitu** [comment]
(not to mention Laravel 5.4 is rumored to be launched in December 2016 or January 2017 and we'll need to support that too)

**Comment by foxtrails** [comment]
Hi @tabacitu : I've just downloaded the demo following the instructions, and still getting a 404 error when trying to hit the /public/admin/register page.

**Comment by foxtrails** [comment]
Hey @tabacitu : Just worked it out. I ditched the 'public' and went with 

backpack-demo/admin/register and voila the page appeared.  In your doco (https://laravel-backpack.readme.io/v3.0/docs/demo) you're referencing public in the URL.

Thanks! :-)

**Comment by OwenMelbz** [comment]
Hi @foxtrails

Thanks for pointing that out.

However it's a little tricky writing it exactly correct, some people use xamp, some artisan, some homestead, some valet, some something else. 

So whatever is written will be wrong for somebody lol

Although for demonstration purposes maybe something like

http://backpack-demo.dev will be the most illustrative?

**Comment by foxtrails** [comment]
Hey Owen...

You in Melbourne mate??? I'm out in Bacchus Marsh, so not far away from you at all! I'm just new to Laravel (past few months) and going through laracasts. Done a heap of training and now ready to actually start writing my project :-)

I've previously used homestead but last week switched to valet, definitely the fastest way to spin up an environment.

I hear what you mean about each environment being different. Hmmmmmm. I suppose you could write a couple of examples in the doco instead of something explicit??

In the end, I went digging through the code to find the route. Ditched the public and then of course, everything worked.

Thanks for the fast reply, really appreciate it mate.
Benjamin

**Comment by OwenMelbz** [comment]
Ha no I'm not anywhere near Australia :D

Sure, more examples the better :) in fact - you can click the "suggest edits" button at the top right and add in some bits you think will benefit new comers! as its hard for people who have been using it for a long time to remember what problems they would have faced back when!
